apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: chaincode-install-carrier-peer0-1-0
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: chaincode-install-carrier-peer0-1-0
  chart:
    git: git@github.com:cryptoprofessor101/blockchain-automation-framework.git
    ref: main
    path: platforms/hyperledger-fabric/charts/install_chaincode
  values:
    metadata:
      namespace: carrier-net
      network:
        version: 2.2.2
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://ab0805ecbb73a45988a4f31e0e50d08b-207072700.ap-south-1.elb.amazonaws.com:8200
      authpath: devcarrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretgitprivatekey: secret/credentials/carrier-net/git?git_password
      tls: false
    orderer:
      address: orderer1.supplychain-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.2
      name: supplychain
      version: 1.0
      lang: golang
      maindirectory: cmd
      repository:
        hostname: "github.com"
        git_username: "cryptoprofessor101"
        url: github.com/cryptoprofessor101/blockchain-automation-framework.git
        branch: develop
        path: examples/supplychain-app/fabric/chaincode_rest_server/chaincode
      endorsementpolicies:  ''
