apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: commit-carrier-allchannel-supplychain1-1
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: commit-carrier-allchannel-supplychain1-1
  chart:
    git: git@github.com:cryptoprofessor101/blockchain-automation-framework.git
    ref: main
    path: platforms/hyperledger-fabric/charts/commit_chaincode
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://ab0805ecbb73a45988a4f31e0e50d08b-207072700.ap-south-1.elb.amazonaws.com:8200
      authpath: devcarrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.supplychain-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.2
      name: supplychain
      version: 1
      sequence: 1
      commitarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
    endorsers:
      creator: carrier-net
      name:  carrier  manufacturer  store  warehouse  
      corepeeraddress:  peer0.carrier-net:7051  peer0.manufacturer-net:7051  peer0.store-net:7051  peer0.warehouse-net:7051 
