apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturer-restserver
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/supplychain-app/charts/fabric-restserver
    git: git@github.com:cryptoprofessor101/blockchain-automation-framework.git
    ref: master
  releaseName: manufacturer-restserver
  values:
    metadata:
      namespace: manufacturer-net
    server:
      name: manufacturer-restserver
      port: 20001
      localmspid: manufacturerMSP
      image: index.docker.io/hyperledgerlabs/supplychain_fabric:rest_server_latest
      username: user1
      cert_path: "/secret/tls/user1.cert"
      key_path: "/secret/tls/user1.pem"
    storage:
      storageclassname: manufacturersc
      storagesize: 512Mi
    vault:
      address: http://127.0.0.1:8200
      role: vault-role
      authpath: devmanufacturer-net-auth
      secretprefix: secret/crypto/peerOrganizations/manufacturer-net
      serviceaccountname: vault-auth
      imagesecretname: regcred
      image: hyperledgerlabs/alpine-utils:1.0
    service:
      servicetype: ClusterIP
      ports:
        apiPort: 20001
        targetPort: 8000
    connection:
      peer: peer0.manufacturer-net
      peerAddress: peer0.manufacturer-net
      peerPort: 7051
      ordererAddress: orderer1.org.com
      ordererPort: 8443