apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: warehouse-expressapi
  namespace: warehouse-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    path: examples/supplychain-app/charts/expressapp
    git: "git@github.com:cryptoprofessor101/blockchain-automation-framework.git"
    ref: "main"
  releaseName: warehousefabric-expressapi
  values:
    nodeName: warehouse-expressapi
    metadata:
      namespace: warehouse-net
    replicaCount: 1
    expressapp:
      serviceType: ClusterIP
      image: index.docker.io/hyperledgerlabs/supplychain_fabric:express_app_latest
      pullPolicy: Always
      pullSecrets: regcred
      nodePorts:
        port: 3000
        targetPort: 3000
        name: tcp
      env:
        apiUrl: http://warehouse-restserver.warehouse-net:20001/api/v1
    proxy:
      provider: none
      name: warehouse
      type: fabric
      external_url_suffix: develop.local.com
      peer_name: peer0
