apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-allchannel-store
  namespace: store-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-allchannel-store
  chart:
    git: git@github.com:cryptoprofessor101/blockchain-automation-framework.git
    ref: main
    path: platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: store-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.store-net:7051
      localmspid: storeMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://adfb01305e9ce4d1fafaafb51264f708-968884330.ap-south-1.elb.amazonaws.com:8200
      authpath: devstore-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/store-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/store-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.supplychain-net:7050
    anchorstx: |-
      CsQCChgKFggCGgYIt4+qiAYiCmFsbGNoYW5uZWwSpwIKpAIKCmFsbGNoYW5uZWwSYRJfCgtBcHBs
      aWNhdGlvbhJQCAESTAoIc3RvcmVNU1ASQBoHCgNNU1ASACILCgdSZWFkZXJzEgAiCwoHV3JpdGVy
      cxIAIgoKBkFkbWlucxIAIg8KC0VuZG9yc2VtZW50EgAasgESrwEKC0FwcGxpY2F0aW9uEp8BCAES
      mgEKCHN0b3JlTVNQEo0BCAEaBwoDTVNQEgAaQQoLQW5jaG9yUGVlcnMSMhIoCiYKIXBlZXIwLnN0
      b3JlLW5ldC5kZXZlbG9wLmxvY2FsLmNvbRD7QRoGQWRtaW5zIgoKBkFkbWlucxIAIg8KC0VuZG9y
      c2VtZW50EgAiCwoHUmVhZGVycxIAIgsKB1dyaXRlcnMSACoGQWRtaW5z

